### 변수 설정 (옵션)
@hostname = localhost
@port = 8080
@baseUrl = http://{{hostname}}:{{port}}/api/v1/auth

### 1. 회원가입 테스트
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "test1234@naver.com",
  "password": "password123!@",
  "nickname": "사용자"
}


### 2. 로그인 테스트
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "test1234@naver.com",
  "password": "password123!@"
}

### 추천 장소
GET http://localhost:8080/api/v1/places/recommend?category=인문(문화/예술/역사)

### 인기 장소
GET http://localhost:8080/api/v1/places/popular
